# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Restart

on:
  workflow_run:
    workflows: ["Deploy"]
    branches: ["master"]
    types:
      - completed
  workflow_dispatch:

jobs:
  restart:
    runs-on: self-hosted

    steps:
    - name: Restart
      run: |
          sudo systemctl restart apps_vrcx_VrcxApi.service